### ISSUE TITLE
Feature: metadata selection list should include all supported metadata types

### ISSUE THREAD

**Issue by clopezramos-everis** [mitxi21/sfdxmetahelper#2]
The metadata selection area should contain all supported metadata types, or at least, there should be a way to add more.

ver. 1.0.1
vscode ver. 1.57.1
sfdx ver. sfdx-cli/7.106.3 win32-x64 node-v14.17.0

**Comment by mitxi21** [comment]
This is already possible, just go to Menu File >> Preferences >> Settings >> Extensions >> SFDX MetaHelper:

![image](https://user-images.githubusercontent.com/1140163/123613090-6ec77900-d803-11eb-89b7-b66ab3ada89b.png)

And then add whatever item you need:

![image](https://user-images.githubusercontent.com/1140163/123613215-87d02a00-d803-11eb-8f1b-92f75dde730b.png)

**Comment by clopezramos-everis** [comment]
oh, nice! thanks! 😃
